### ISSUE TITLE
Xamarin Forms -Elements cannot be clicked when scrollview is scrolled down

### ISSUE THREAD

**Issue by infinitbis** [rashidmakki/testing#46]
I just upgraded my Xamarin Forms to version 4.7.0.968 and all my pages with a ScrollView don't work the moment the scroll bar is move from the top position. You can fill everything in the form if the scroll bar is at the top, then when the scroll bar is scrolled downwards everything stops working on the page. e.g. you can click a text box in row 5 and the cursor will highlight the element in row 1. but if you put the scroll bar back to the top, the mouse will select the exact element you have clicked on

**Comment by infinitbis** [comment]
'/label Xamarin Forms ScrollView

**Comment by rashidmakki** [comment]
I did not understand what kind of form are you talking about?

**Comment by rashidmakki** [comment]
for adding label it should be "/label XamarinFormsScrollView " .

**Comment by infinitbis** [comment]
> I did not understand what kind of form are you talking about?

Any form with a scroll view. the moment you scroll down the page, you wont be able to click on any element on it. If you scroll back to the top, everything becomes clickable again

**Comment by rashidmakki** [comment]
Never used Xamarin till now .May be this can help you https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/scrollview .

**Comment by infinitbis** [comment]
my project has been working all along until i upgraded XamarinForms to 4.7.0.968. If i roll back it works

**Comment by rashidmakki** [comment]
If there is no error then may be bug issue. You should report here https://github.com/xamarin/Xamarin.Forms/issues.

**Comment by infinitbis** [comment]
> If there is no error then may be bug issue. You should report here https://github.com/xamarin/Xamarin.Forms/issues.

this got closed but i still hvnt found the solution. it must be a bug in xamarin forms 4.7 coz the versions before it are working just fine
